{% set name = "fractal-server" %}
{% set version = "1.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fractal_server-{{ version }}.tar.gz
  sha256: 451b50928a1ef83c8e32b81ffaa45d4db752edf0702aefe1371ebeb9f97e63f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - fractalctl = fractal_server.__main__:run
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - packaging >=23.2.0,<24.0.0
    - bcrypt 4.0.1
    - python >=3.9.0,<4.0.0
    - python-dotenv >=0.21.0,<0.22.0
    - fastapi >=0.109.0,<0.110.0
    - sqlmodel >=0.0.14,<0.0.15
    - aiosqlite >=0.19.0,<0.20.0
    - fastapi-users >=12.1.0,<13.0.0
    - alembic >=1.9.1,<2.0.0
    - uvicorn >=0.27.0,<0.28.0
    - sqlalchemy >=2.0.23,<2.1
    - pydantic >=1.10.8,<2
  run_constrained:
    - clusterfutures >=0.5.0,<0.6.0
    - cloudpickle >=2.2.1,<2.3.0
    - asyncpg >=0.27.0,<0.28.0
    - psycopg2 >=2.9.5,<3.0.0
    - gunicorn >=20.1.0,<21.0.0

test:
  imports:
    - fractal_server
  commands:
    - pip check
    - fractalctl --help
  requires:
    - pip

about:
  home: https://github.com/fractal-analytics-platform/fractal-server
  summary: Server component of the Fractal analytics platform
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ychiucco
    - jluethi
    - mfranzon
    - tcompa
