{% set python_min = "3.12.0" %}
{% set name = "fractal-server" %}
{% set version = "2.23.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fractal_server-{{ version }}.tar.gz
  sha256: 2efbb99f8babb2d4eef84ae310458697dae01aee30a8b262bcd567fdbce68b25

build:
  entry_points:
    - fractalctl = fractal_server.__main__:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.9.18,<0.10.0
    - pip
  run:
    - httpx
    - httpx-oauth
    - invoke
    - paramiko >=5.0.0,<5.1.0
    - starlette >=1.3.1
    - tomli-w >=1.2.0,<1.3.0
    - python >={{ python_min }},<3.15
    - fastapi >=0.137.2,<0.138.0
    - sqlmodel ==0.0.38
    - sqlalchemy >=2.0.23,<2.1
    - fastapi-users >=15,<16
    - alembic >=1.13.1,<2.0.0
    - uvicorn >=0.46.0,<0.47.0
    - uvicorn-worker ==0.4.0
    - pydantic >=2.13.0,<2.14.0
    - pydantic-settings ==2.14.0
    - packaging >=26.0.0,<27.0.0
    - fabric >=3.2.2,<3.3.0
    - gunicorn >=26,<27
    - psycopg >=3.1.0,<4.0.0

test:
  imports:
    - fractal_server
  commands:
    - pip check
    - fractalctl --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fractal-analytics-platform/fractal-server
  summary: Backend component of the Fractal analytics platform
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ychiucco
    - jluethi
    - mfranzon
    - tcompa
